name: Show Success Message on Push

on:
  push:
    branches:
      - main
      - contact-page

jobs:
  say-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print success message
        run: echo "✅ Push was successful! Great job, Prex!"
